# This Is a Markdown Block
Use 1 hash for Big size Font


## This is a 2nd Markdown
Use 2 hash for small than 1st size

### This is a 2nd Markdown

Use 3 hash for smaller size font then 2

In [23]:
print("This is a Python Block")

This is a Python Block


## Importing Required Libraries

In [24]:
import numpy as np


In [25]:
# For install Library
# ! pip install numpy

Initializing Array with the help of numpy


In [26]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [27]:
# Multiply array by 2
arr=arr*2
print(arr)

[ 2  4  6  8 10]


In [28]:
# Check Shape of array which have 5 element 
# and shape is 1 D 
arr.shape

(5,)

In [33]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
arr1.shape  # shape : 2 is rows and ,3 is element in a row 

[[1 2 3]
 [4 5 6]]


(2, 3)

In [36]:
# Access element on the Basis of Index
# ! 4 is available in array at index 1
print(arr)
arr[1]

[ 2  4  6  8 10]


np.int64(4)

In [40]:
# Slicing Extract [4 6 8]
arr[1:4]

array([4, 6, 8])

## Creating a 2-Dimnsional Array

In [47]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.shape # (3,4) 3 rows and 4 ele
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
# Extract Element in a 2D or 3D array
# ! a[rows,col] : Rows and col are Indexed from 0
a[1,3]

np.int64(8)

In [52]:
#  Check Dimension of the array named a 
a.ndim

2

In [ ]:
# Check Total Number of element
a.size

12

Get a Sub matrix from [[2,3,4,5,6],[9,8,7,6,5]]

In [ ]:
matrix=np.array([[2,3,4,5,6],[9,8,7,6,5]])
matrix[:,2:]
# empty means all element: Not defined start and step point
# Index 2 means take ele from index 2 from every rows

array([[4, 5, 6],
       [7, 6, 5]])

Zero Matrix 


In [58]:
zero_matrix=np.zeros((3,4))
zero_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

One Matrix where all ele are 1


In [59]:
one_matrix=np.ones((2,3))
one_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
empty_matrix=np.empty((2,3))
empty_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Add Elemet from 0 to 9
range_of_num=np.arange(10)
range_of_num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Add Element with 2 steps from 0 to 9
range_with_step=np.arange(0,10,2) # start,stop,step
range_with_step

array([0, 2, 4, 6, 8])

In [66]:
#   Sorting array 
# ! Time complexity: Aberage and Worst  O(nlogn)
# * Works on Merge + Insertion= Tim Sort

arr=np.array([5,3,2,9,10])
arr.sort()
arr

array([ 2,  3,  5,  9, 10])

In [ ]:

# ! Error Beacuse both aray have different Dimention 
x=np.array([[1,2],[3,4]])
y=np.array([5,6])
np.concatenate((x,y),axis=0) # Concatenating two arrays along axis 0

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:

# ! Executed
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
# ! Row wise 
np.concatenate((x,y),axis=0)
# ! Column Wise
np.concatenate((x,y),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])