# This Is a Markdown Block
Use 1 hash for Big size Font


## This is a 2nd Markdown
Use 2 hash for small than 1st size

### This is a 2nd Markdown

Use 3 hash for smaller size font then 2

In [23]:
print("This is a Python Block")

This is a Python Block


## Importing Required Libraries

In [24]:
import numpy as np


In [25]:
# For install Library
# ! pip install numpy

Initializing Array with the help of numpy


In [26]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [27]:
# Multiply array by 2
arr=arr*2
print(arr)

[ 2  4  6  8 10]


In [28]:
# Check Shape of array which have 5 element 
# and shape is 1 D 
arr.shape

(5,)

In [33]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
arr1.shape  # shape : 2 is rows and ,3 is element in a row 

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
# Access element on the Basis of Index
# ! 4 is available in array at index 1
arr[1]

np.int64(4)